# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs
# https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers

name: mutation-test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *"
  
jobs:
  # These tests run in standard node containers with their db attached as a service
  mutation-database-tests:
    strategy:
      fail-fast: false
      matrix:
        node-container: ["node:18"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    uses: ./.github/workflows/database-tests.yml
    with:
      node-container: ${{matrix.node-container}}
      run-type: 'mutation'
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}


  # These tests run with custom docker image attributes that can't be specified in a GHA service
  mutation-database-compose-tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    uses: ./.github/workflows/database-compose-tests.yml
    with:
      node-version: ${{matrix.node-version}}
      run-type: 'mutation'
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
