name: tests-windows
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
      shard:
        required: false
        type: number
        default: 1
      total-shards:
        required: false
        type: number
        default: 1

jobs:
  better-sqlite3:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: build/

      - run: pnpm install
      - run: cp .github/workflows/test/better-sqlite3.ormconfig.json ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci --shard=${{ inputs.shard }}/${{ inputs.total-shards }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: better-sqlite3-node:${{ inputs.shard }}/${{ inputs.total-shards }}-${{ inputs.node-version }}-windows
          parallel: true

  sqlite:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: build/

      - run: pnpm install
      - run: cp .github/workflows/test/sqlite.ormconfig.json ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci --shard=${{ inputs.shard }}/${{ inputs.total-shards }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: sqlite-node:${{ inputs.shard }}/${{ inputs.total-shards }}-${{ inputs.node-version }}-windows
          parallel: true

  sqljs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: build/

      - run: pnpm install
      - run: cp .github/workflows/test/sqljs.ormconfig.json ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci --shard=${{ inputs.shard }}/${{ inputs.total-shards }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: sqljs-node:${{ inputs.shard }}/${{ inputs.total-shards }}-${{ inputs.node-version }}-windows
          parallel: true
